name: sadykova_app
description: A new Flutter project.
version: 1.0.1+3
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ###
  logger: ^1.1.0
  dartz: ^0.10.1
  flutter_svg: ^0.22.0
  shimmer: ^2.0.0
  connectivity_plus: ^5.0.2
  dio: ^4.0.0
  flutter_dotenv: ^5.0.0
  mask_text_input_formatter: ^2.1.0
  easy_mask: ^2.0.1
  persistent_bottom_nav_bar: ^4.0.2
  carousel_slider: ^4.1.1
  sliding_up_panel: ^2.0.0+1
  modal_bottom_sheet: ^2.0.0
  cached_network_image: ^3.1.0
  expandable: ^5.0.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  table_calendar: ^3.0.6
  flutter_html: ^2.2.1
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.5
  lottie: ^1.4.2
  pinput: ^2.2.16
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
  http_parser: ^4.0.0
  flutter_cached_pdfview: ^0.4.1
  yandex_mapkit: ^3.3.3
  webview_flutter:
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.0
  flutter_launcher_icons: ^0.11.0
  
flutter_native_splash:
  color: "#F5EEE6"
  image: assets/images/logo/logo.png

# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/app_icon.png"
flutter:
  uses-material-design: true

  assets:
    - assets/icons/logo/
    - assets/icons/appointment/
    - assets/icons/profile/
    - assets/icons/main/
    - assets/icons/nav_bar/
    - assets/images/user/
    - assets/images/bg/
    - assets/images/others/
    - assets/images/logo/
    - assets/images/map/
    - assets/images/placeholder/
    - assets/lottie/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-bold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-b
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf